---
title: "Analyse exploratoire"
output: html_document
date: '2022-08-24'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Import des données

```{r,eval=FALSE}
pacman::p_load(data.table,tidyverse)

type_document=c("html_document","html2")
type_document=c("revealjs::revealjs_presentation","revealjs_ma")
type_document=c("pdf_document","pdf_sanslogo")
type_document=c("beamer_presentation","beamer")

######### render fichiers #############

for (file in files1[1:3]){
  render(file,type_document[1],
         encoding="UTF-8",
         output_dir = type_document[2],
         quiet = T)
  
}


```

mono

```{r}
mono19=fread("data/Mono/PM_ALM_MonoSupport_31122019.csv",skip=2)%>%
  mutate(PM_ALM=as.numeric(gsub(" ","",PM_ALM)))
mono20=fread("data/Mono/PM_ALM_MonoSupport_31122020.csv",skip=2)%>%
  mutate(PM_ALM=as.numeric(gsub(" ","",PM_ALM)))
mono21=fread("data/Mono/PM_ALM_MonoSupport_31122021.csv",skip=2)%>%
  mutate(PM_ALM=as.numeric(gsub(" ","",PM_ALM)))

multi20=fread("data/Multi/PM_ALM_Multisupports_31122020.csv",skip=2)

mono20=fread("data/Mono/PM_ALM_MonoSupport_31122020.csv",skip=2)%>%
  mutate(PM_ALM=as.numeric(gsub(" ","",PM_ALM)))
mono21=fread("data/Mono/PM_ALM_MonoSupport_31122021.csv",skip=2)%>%
  mutate(PM_ALM=as.numeric(gsub(" ","",PM_ALM)))



```


```{r}
summary(mono19)
```

```{r}

cols_to_delete <- colnames(mono19)[colSums(is.na(mono19)) == nrow(mono19)] # get the names of the columns that have only NA values

set(mono19, j = cols_to_delete, value = NULL)

summary(mono19)

```


```{r}
mono19[, colnames(mono19)[colSums(is.null(mono19)) == nrow(mono19)] := NULL]

mono19[, apply(mono19, 2, function(x) any(!as.character(x) == "null")), drop = FALSE] 

is.null(data.frame(mono19))

subset(mono19, select = -which(colSums(is.null(mono19)) == nrow(mono19)))

```




```{r}
mono20[is.na(PM_ALM)]

mono20[115095]

mono=merge(mono19,mono20,by="NoPolice")

names(mono19)==
names(mono20)

dim(mono19)
dim(mono20)



```


```{r}
mono19[,.N,by=Matricule]



mono19$taux2020=mono19$Valeur.2020/mono19$Valeur.2019-1

hist(mono19[CODE=="R0005"]$taux2020)



sal=mono19[CODE %in% c("T0004","R0005"),c("Matricule","Genre","CODE","Début","Fin","Date.de.Naissance","Grille","Valeur.2019")]%>%
  pivot_wider(names_from = "CODE",values_from ="Valeur.2019")%>%
  mutate(sal_hor=R0005/T0004)%>%
  filter(is.na(sal_hor)==F)%>%
  data.table()

hist(sal$sal_hor,nclass=100)

sal[,.N,by="Grille"]

ggplot(sal,aes(Date.de.Naissance,sal_hor,color=as.factor(Genre)))+ geom_point()
ggplot(sal,aes(Date.de.Naissance,sal_hor,color=as.factor(Grille)))+ geom_point()

min(sal$sal_hor)

mono19[CODE %in% c("T0004","R0005"),c("Matricule","Genre","CODE","Valeur.2019")][,.N,by=Matricule]

mono19[CODE %in% c("T0004","R0005") & Matricule=="65",c("Matricule","Genre","CODE","Valeur.2019")]



mono19[ CODE %in% c("T0004","R0005") &Matricule=="65",]

unique(mono19)



```



```{r}
multi20=fread("data/Multi/PM_ALM_Multisupports_31122020.csv",skip=3)


r19=fread("data/Rente/PM_ALM_RMC_Reserve_31122019.csv",skip=2)

ggplot(r19,aes(Provision_autre_risque,Capital_Garanti))+geom_point()


```

Année de naissance

min trop faible

```{r}
min(mono20$AnneeNaissanceAssure)
max(mono20$AnneeNaissanceAssure)

hist(mono20$AnneeNaissanceAssure)
```

NoPolice ne correspond pas, donc on ne peut pas étudier l'évolution

```{r}
mono20[115098]
mono19[115098]

mono19[,.N,by=TypeDePolice]


mono19[,.N,by=TauxChargementSurEncours]
```


```{r}
mono20$PM_ALM

ggplot(mono20,aes(AnneeNaissanceAssure,PM_ALM,color=as.factor(SexeAssure)))+geom_point()

plot(mono20$PM_ALM,mono20$AnneeNaissanceAssure)
```




